spring:
  application:
    name: TPO_04_Books
  h2:
    console:
      path: /console
  datasource:
    url: jdbc:h2:mem:books
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql-data/data.sql
